language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_script:
  - echo -e "Host $DEPLOYHOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: phpunit --verbose .
branches:
  only:
    - master
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - openssl aes-256-cbc -K $encrypted_d4b6cdb49290_key -iv $encrypted_d4b6cdb49290_iv -in perl_rsa.enc -out deploy_rsa -d
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $SSHUSER@$DEPLOYHOST:$DEPLOYPATH
  on:
  branch: master
