language: php
php:
  - '7.0'
before_script:
  - echo -e "Host $DEPLOYHOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: phpunit --verbose .
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_5e7c56201796_key -iv $encrypted_5e7c56201796_iv -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $SSHUSER@$DEPLOYHOST:$DEPLOYPATH
  on:
  branch: master
  